// Generated by tools/gen_model_params.py -- do not edit.
// model.tflite 86048 bytes, sha256 a88ce6d7a98685c2...
#pragma once

#define MODEL_FE_SPEC_VERSION 2
#define MODEL_FE_VARIANT      2
#define MODEL_FRAMES          44
#define MODEL_FEATS           12
#define MODEL_INPUTS          528
#define MODEL_LOOKAHEAD       2
#define MODEL_BLOCK_SAMPLES   512
#define MODEL_SAMPLE_RATE     48000
#define MODEL_TFLITE_BYTES    86048u
#define MODEL_TFLITE_FNV1A    0x5c91e7bfcd78f097ULL

// Positions into the interpreter's output list, taken from the
// SignatureDef. NOT the order the heads are written down in, and not
// stable across exports: adding the music head moved all three of the
// others, even though it is last in the signature.
#define MODEL_OUT_BEAT        2   // shape [1, 1], scale 0.00390625, zero -128
#define MODEL_OUT_BEAT_OFFSET 3   // shape [1, 1], scale 0.00390625, zero -128
#define MODEL_OUT_HIT         1   // shape [1, 4], scale 0.00390625, zero -128
#define MODEL_OUT_MUSIC       0   // shape [1, 1], scale 0.00390625, zero -128

#define MODEL_IN_SCALE        0.0741002634168f
#define MODEL_IN_ZERO         (-96)
#define MODEL_OUT_SCALE       0.00390625f
#define MODEL_OUT_ZERO        (-128)

// Normalisation folded with input quantisation:
//   q = lrintf((x - mean[k]) * qmul[k]) + MODEL_IN_ZERO
static const float kModelNormMean[MODEL_FEATS] = {
    0.22018601f, 0.193126261f, 0.203819901f, 0.136355281f, 0.00942203682f, 0.0209678672f, 0.0207058061f, 0.0196072776f, 0.156659648f, 0.0280151274f, 0.0188773945f, 82.1383896f
};
static const float kModelQuantMul[MODEL_FEATS] = {
    54.4599915f, 56.928154f, 56.260849f, 69.7642899f, 688.086121f, 202.991562f, 205.378571f, 213.777985f, 63.9065323f, 165.754257f, 179.325043f, 0.988741815f
};

