// Generated by tools/gen_model_params.py -- do not edit.
// model.tflite 86048 bytes, sha256 fb9ac4ebfbe0c8cd...
#pragma once

#define MODEL_FE_SPEC_VERSION 2
#define MODEL_FE_VARIANT      2
#define MODEL_FRAMES          44
#define MODEL_FEATS           12
#define MODEL_INPUTS          528
#define MODEL_LOOKAHEAD       2
#define MODEL_BLOCK_SAMPLES   512
#define MODEL_SAMPLE_RATE     48000
#define MODEL_TFLITE_BYTES    86048u
#define MODEL_TFLITE_FNV1A    0x2b6258569ccb5cecULL

// Positions into the interpreter's output list, taken from the
// SignatureDef. NOT the order the heads are written down in, and not
// stable across exports: adding the music head moved all three of the
// others, even though it is last in the signature.
#define MODEL_OUT_BEAT        2   // shape [1, 1], scale 0.00390625, zero -128
#define MODEL_OUT_BEAT_OFFSET 3   // shape [1, 1], scale 0.00390625, zero -128
#define MODEL_OUT_HIT         1   // shape [1, 4], scale 0.00390625, zero -128
#define MODEL_OUT_MUSIC       0   // shape [1, 1], scale 0.00390625, zero -128

#define MODEL_IN_SCALE        0.0707311406732f
#define MODEL_IN_ZERO         (-94)
#define MODEL_OUT_SCALE       0.00390625f
#define MODEL_OUT_ZERO        (-128)

// Normalisation folded with input quantisation:
//   q = lrintf((x - mean[k]) * qmul[k]) + MODEL_IN_ZERO
static const float kModelNormMean[MODEL_FEATS] = {
    0.218913943f, 0.19191651f, 0.204607591f, 0.136631757f, 0.00955685321f, 0.0214877035f, 0.0212332811f, 0.0201605503f, 0.156394288f, 0.0287562292f, 0.0193065163f, 85.01194f
};
static const float kModelQuantMul[MODEL_FEATS] = {
    57.8378029f, 60.2977295f, 59.6582947f, 73.4682846f, 711.523315f, 208.688049f, 210.914032f, 219.007309f, 67.0997543f, 169.996155f, 184.055038f, 0.981784225f
};

