#!/usr/bin/env python3
"""Generate model_params.h and mel_filters.h from the two-stage export.

Derived rather than transcribed: every one of these values fails silently if
stale. The output indices come from the SignatureDef, because the converter
does not order subgraph outputs the way the signature lists them and the order
changes between exports.
"""
import json
import sys
from pathlib import Path

import tflite

FE_ORDER = ["level", "bands0", "bands1", "bands2", "rms",
            "flux0", "flux1", "flux2", "fund_rms", "mid_flux",
            "treble_flux", "spl_db"]
X_ORDER = FE_ORDER + [f"mel_flux{i}" for i in range(16)]


def fnv1a64(data):
    h = 0xcbf29ce484222325
    for b in data:
        h = ((h ^ b) * 0x100000001b3) & 0xFFFFFFFFFFFFFFFF
    return h


def f(v):
    """A C float literal; bare '0f' is not one."""
    s = f"{v:.9g}"
    if "." not in s and "e" not in s and "E" not in s and "inf" not in s:
        s += ".0"
    return s + "f"


def load(path, heads):
    raw = Path(path).read_bytes()
    m = tflite.Model.GetRootAsModel(raw, 0)
    sg = m.Subgraphs(0)
    if m.SignatureDefsLength() != 1:
        sys.exit(f"{path}: expected exactly one SignatureDef")
    sig = m.SignatureDefs(0)

    outs = list(sg.OutputsAsNumpy())
    pos = {}
    for k in range(sig.OutputsLength()):
        t = sig.Outputs(k)
        idx = t.TensorIndex()
        if idx not in outs:
            sys.exit(f"{path}: signature output {t.Name().decode()} is not a subgraph output")
        pos[t.Name().decode()] = outs.index(idx)
    if sorted(pos) != sorted(heads):
        sys.exit(f"{path}: signature heads {sorted(pos)} != {sorted(heads)}")

    inp = sg.Tensors(int(sg.InputsAsNumpy()[0]))
    q = inp.Quantization()

    def outq(name):
        t = sg.Tensors(outs[pos[name]])
        qq = t.Quantization()
        return float(qq.ScaleAsNumpy()[0]), int(qq.ZeroPointAsNumpy()[0]), \
            t.ShapeAsNumpy().tolist()

    return dict(raw=raw, pos=pos, outq=outq,
                in_scale=float(q.ScaleAsNumpy()[0]),
                in_zero=int(q.ZeroPointAsNumpy()[0]),
                in_shape=inp.ShapeAsNumpy().tolist())


def emit_mel(meta, out_path):
    mel = meta["features"]["mel"]
    fb = mel["filterbank"]
    nbins = max(b["start_bin"] + len(b["weights"]) for b in fb)
    flat = [w for b in fb for w in b["weights"]]

    L = ["// Generated by tools/gen_model_params.py -- do not edit.",
         "// Mel filterbank from model_meta.json: the 40 HTK triangles",
         f"// {mel['source_triangles']['lo_hz']}-{mel['source_triangles']['hi_hz']} Hz merged into"
         f" {len(fb)} groups.",
         "#pragma once",
         "",
         f"#define MEL_BANDS  {len(fb)}",
         f"#define MEL_BINS   {nbins}   // FFT bins the filterbank reaches",
         f"#define MEL_WEIGHTS {len(flat)}",
         "",
         "static const int kMelStart[MEL_BANDS] = {",
         "    " + ", ".join(str(b["start_bin"]) for b in fb),
         "};",
         "static const int kMelLen[MEL_BANDS] = {",
         "    " + ", ".join(str(len(b["weights"])) for b in fb),
         "};",
         "static const float kMelWeights[MEL_WEIGHTS] = {"]
    for i in range(0, len(flat), 6):
        L.append("    " + ", ".join(f(v) for v in flat[i:i + 6]) + ",")
    L += ["};", ""]
    Path(out_path).write_text("\n".join(L) + "\n")
    return fnv1a64(json.dumps(fb, sort_keys=True).encode())


def main(model_dir, out_params, out_mel, fe_spec_version):
    d = Path(model_dir)
    meta = json.loads((d / "model_meta.json").read_text())

    if meta["format"] != "two-stage-1":
        sys.exit(f"format {meta['format']!r}, expected 'two-stage-1'")
    if meta["features"]["order"] != X_ORDER:
        sys.exit(f"feature order mismatch:\n {meta['features']['order']}\n {X_ORDER}")
    if meta["fe_spec_version"] != fe_spec_version:
        sys.exit(f"model fe_spec_version {meta['fe_spec_version']} != firmware {fe_spec_version}")

    mel = meta["features"]["mel"]
    if mel["window"] != 1024 or mel["fft"] != 1024:
        sys.exit(f"mel window/fft {mel['window']}/{mel['fft']}, melflux.c assumes 1024")
    mel_hash = emit_mel(meta, out_mel)

    a = load(d / meta["stage_a"]["file"], ["beat"])
    b = load(d / meta["stage_b"]["file"], ["beat", "beat_offset", "hit", "music"])

    ctx = meta["context"]
    for st, m, name in ((meta["stage_a"], a, "A"), (meta["stage_b"], b, "B")):
        if len(m["raw"]) != st["tflite_bytes"]:
            sys.exit(f"stage {name} is {len(m['raw'])} bytes, meta says {st['tflite_bytes']}")
        if m["in_shape"] != [1, ctx["inputs_per_stage"]]:
            sys.exit(f"stage {name} input {m['in_shape']} != [1, {ctx['inputs_per_stage']}]")
        if abs(m["in_scale"] - st["input_scale"]) > 1e-12 or m["in_zero"] != st["input_zero_point"]:
            sys.exit(f"stage {name} quantisation disagrees with meta")
        for head, spec in st["outputs"].items():
            sc, zp, _ = m["outq"](head)
            if abs(sc - spec["scale"]) > 1e-12 or zp != spec["zero_point"]:
                sys.exit(f"stage {name} head {head} quantisation disagrees with meta")

    pa, pb = meta["stage_a"]["projection"], meta["stage_b"]["projection"]
    if len(pa["weights"]) != 28 or len(pb["weights"]) != 29:
        sys.exit("projection shapes are not 28x12 and 29x12")
    nf = ctx["frames"] and len(pa["weights"][0])

    out_scale, out_zero, _ = b["outq"]("beat")

    L = []
    w = L.append
    w("// Generated by tools/gen_model_params.py -- do not edit.")
    w(f"// stage_a {len(a['raw'])} bytes sha256 {meta['stage_a']['sha256'][:16]}...")
    w(f"// stage_b {len(b['raw'])} bytes sha256 {meta['stage_b']['sha256'][:16]}...")
    w("#pragma once")
    w("")
    w("#include \"mel_filters.h\"")
    w("")
    w(f"#define MODEL_FE_SPEC_VERSION {meta['fe_spec_version']}")
    w(f"#define MODEL_FE_VARIANT      {meta['fe_variant']}")
    w(f"#define MODEL_FRAMES          {ctx['frames']}")
    w(f"#define MODEL_FEATS           {nf}")
    w(f"#define MODEL_INPUTS          {ctx['inputs_per_stage']}")
    w(f"#define MODEL_LOOKAHEAD       {ctx['lookahead_blocks']}")
    w(f"#define MODEL_RING_BLOCKS     {ctx['ring_blocks']}")
    w(f"#define MODEL_BLOCK_SAMPLES   {meta['block_samples']}")
    w(f"#define MODEL_SAMPLE_RATE     {meta['sample_rate']}")
    w(f"#define MODEL_X_FEATS         {len(X_ORDER)}   // 12 front end + 16 mel flux")
    w(f"#define MODEL_MEL_FNV1A       0x{mel_hash:016x}ULL  // mel_filters.h came from this export")
    w("")
    w("// Stage A: the same trunk shape as the single-stage model, beat only.")
    w(f"#define MODEL_A_BYTES         {len(a['raw'])}u")
    w(f"#define MODEL_A_FNV1A         0x{fnv1a64(a['raw']):016x}ULL")
    w(f"#define MODEL_A_IN_SCALE      {f(a['in_scale'])}")
    w(f"#define MODEL_A_IN_ZERO       ({a['in_zero']})")
    sc, zp, _ = a["outq"]("beat")
    w(f"#define MODEL_A_OUT_BEAT      {a['pos']['beat']}   // scale {sc}, zero {zp}")
    w(f"#define MODEL_A_OUT_SCALE     {f(sc)}")
    w(f"#define MODEL_A_OUT_ZERO      ({zp})")
    w("")
    w("// Stage B sees the same audio plus stage A's beat from MODEL_FB_SHIFT")
    w("// blocks back, and carries every head the firmware uses.")
    w(f"#define MODEL_B_BYTES         {len(b['raw'])}u")
    w(f"#define MODEL_B_FNV1A         0x{fnv1a64(b['raw']):016x}ULL")
    w(f"#define MODEL_B_IN_SCALE      {f(b['in_scale'])}")
    w(f"#define MODEL_B_IN_ZERO       ({b['in_zero']})")
    w(f"#define MODEL_FB_SHIFT        {meta['stage_b']['feedback']['shift_blocks']}")
    w("")
    w("// Positions into the interpreter's output list, taken from the")
    w("// SignatureDef. NOT the order the heads are written down in, and not")
    w("// stable across exports: adding the music head moved all three of the")
    w("// others, even though it is last in the signature.")
    for name in ("beat", "beat_offset", "hit", "music"):
        sc, zp, shp = b["outq"](name)
        w(f"#define MODEL_OUT_{name.upper():<11} {b['pos'][name]}   "
          f"// shape {shp}, scale {sc}, zero {zp}")
    w(f"#define MODEL_OUT_SCALE       {f(out_scale)}")
    w(f"#define MODEL_OUT_ZERO        ({out_zero})")
    w("")
    w("// Per-block projections, normalisation folded in: applied to the raw")
    w("// features, so there is no (x - mean) / scale step.")
    w("//   p[j] = bias[j] + sum_i x[i] * W[i][j]")

    def table(name, rows, n):
        w(f"static const float {name}[{n}][MODEL_FEATS] = {{")
        for r in rows:
            w("    {" + ", ".join(f(v) for v in r) + "},")
        w("};")

    table("kProjAW", pa["weights"], "MODEL_X_FEATS")
    w("static const float kProjAB[MODEL_FEATS] = {")
    w("    " + ", ".join(f(v) for v in pa["bias"]))
    w("};")
    table("kProjBW", pb["weights"], "(MODEL_X_FEATS + 1)")
    w("static const float kProjBB[MODEL_FEATS] = {")
    w("    " + ", ".join(f(v) for v in pb["bias"]))
    w("};")
    w("")
    Path(out_params).write_text("\n".join(L) + "\n")
    print(f"wrote {out_params} and {out_mel}: "
          f"B outputs beat={b['pos']['beat']} beat_offset={b['pos']['beat_offset']} "
          f"hit={b['pos']['hit']} music={b['pos']['music']}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3], int(sys.argv[4]))
