#!/usr/bin/env python3
"""Generate model_params.h from model.tflite + model_meta.json.

Derived rather than transcribed: every one of these values fails silently if
stale. The output indices come from the SignatureDef, because the converter
does not order subgraph outputs the way the signature lists them and the order
changes between exports.
"""
import json
import sys
from pathlib import Path

import tflite

FEATURE_ORDER = ["level", "bands0", "bands1", "bands2", "rms",
                 "flux0", "flux1", "flux2", "fund_rms", "mid_flux",
                 "treble_flux", "spl_db"]


def fnv1a64(data):
    h = 0xcbf29ce484222325
    for b in data:
        h = ((h ^ b) * 0x100000001b3) & 0xFFFFFFFFFFFFFFFF
    return h


def main(model_path, meta_path, out_path, fe_spec_version):
    raw = Path(model_path).read_bytes()
    meta = json.loads(Path(meta_path).read_text())
    m = tflite.Model.GetRootAsModel(raw, 0)
    sg = m.Subgraphs(0)

    if meta["feature_order"] != FEATURE_ORDER:
        sys.exit(f"feature_order mismatch:\n {meta['feature_order']}\n {FEATURE_ORDER}")
    if meta["sha256"] and len(raw) != meta["tflite_bytes"]:
        sys.exit(f"model is {len(raw)} bytes, meta says {meta['tflite_bytes']}")

    # fe_spec_version: the delivered model records 1 because the corpus predates
    # v2, but it was trained on fe_variant 2, which IS v2 -- v2 is defined as v1
    # built with -DFE_NO_COMB and is bit-identical to it (verified over 7498
    # blocks of real capture). Accept that one pairing and say so loudly.
    spec = meta["fe_spec_version"]
    variant = meta["fe_variant"]
    if spec == 1 and variant == 2 and fe_spec_version == 2:
        print("NOTE: model_meta records fe_spec_version 1 with fe_variant 2; "
              "treating as v2 (identical features). Re-export to clear this.")
        spec = 2
    if spec != fe_spec_version:
        sys.exit(f"model fe_spec_version {spec} != firmware {fe_spec_version}")

    sig = None
    for i in range(m.SignatureDefsLength()):
        sig = m.SignatureDefs(i)
    if sig is None:
        sys.exit("model has no SignatureDef; cannot map outputs safely")

    outs = list(sg.OutputsAsNumpy())
    by_name = {}
    for k in range(sig.OutputsLength()):
        t = sig.Outputs(k)
        name = t.Name().decode()
        idx = t.TensorIndex()
        if idx not in outs:
            sys.exit(f"signature output {name} -> tensor {idx} is not a subgraph output")
        by_name[name] = outs.index(idx)
    for need in ("beat", "beat_offset", "hit", "music"):
        if need not in by_name:
            sys.exit(f"signature has no output named {need}: {list(by_name)}")

    inp = sg.Tensors(int(sg.InputsAsNumpy()[0]))
    q = inp.Quantization()
    in_scale = q.ScaleAsNumpy()[0]
    in_zero = int(q.ZeroPointAsNumpy()[0])
    in_shape = inp.ShapeAsNumpy().tolist()
    if in_shape != [1, meta["context"]["inputs"]]:
        sys.exit(f"input shape {in_shape} != [1, {meta['context']['inputs']}]")

    def outq(pos):
        t = sg.Tensors(outs[pos])
        qq = t.Quantization()
        return float(qq.ScaleAsNumpy()[0]), int(qq.ZeroPointAsNumpy()[0]), \
            t.ShapeAsNumpy().tolist()

    mean = meta["normalisation"]["mean"]
    scale = meta["normalisation"]["scale"]
    ctx = meta["context"]

    L = []
    w = L.append
    w("// Generated by tools/gen_model_params.py -- do not edit.")
    w(f"// model.tflite {len(raw)} bytes, sha256 {meta['sha256'][:16]}...")
    w("#pragma once")
    w("")
    w(f"#define MODEL_FE_SPEC_VERSION {spec}")
    w(f"#define MODEL_FE_VARIANT      {variant}")
    w(f"#define MODEL_FRAMES          {ctx['frames']}")
    w(f"#define MODEL_FEATS           {len(FEATURE_ORDER)}")
    w(f"#define MODEL_INPUTS          {ctx['inputs']}")
    w(f"#define MODEL_LOOKAHEAD       {ctx['lookahead_blocks']}")
    w(f"#define MODEL_BLOCK_SAMPLES   {meta['block_samples']}")
    w(f"#define MODEL_SAMPLE_RATE     {meta['sample_rate']}")
    w(f"#define MODEL_TFLITE_BYTES    {len(raw)}u")
    w(f"#define MODEL_TFLITE_FNV1A    0x{fnv1a64(raw):016x}ULL")
    w("")
    w("// Positions into the interpreter's output list, taken from the")
    w("// SignatureDef. NOT the order the heads are written down in, and not")
    w("// stable across exports: adding the music head moved all three of the")
    w("// others, even though it is last in the signature.")
    for name in ("beat", "beat_offset", "hit", "music"):
        sc, zp, shp = outq(by_name[name])
        w(f"#define MODEL_OUT_{name.upper():<11} {by_name[name]}   "
          f"// shape {shp}, scale {sc}, zero {zp}")
    w("")
    w(f"#define MODEL_IN_SCALE        {in_scale:.12g}f")
    w(f"#define MODEL_IN_ZERO         ({in_zero})")
    sc, zp, _ = outq(by_name["beat"])
    w(f"#define MODEL_OUT_SCALE       {sc:.12g}f")
    w(f"#define MODEL_OUT_ZERO        ({zp})")
    w("")
    w("// Normalisation folded with input quantisation:")
    w("//   q = lrintf((x - mean[k]) * qmul[k]) + MODEL_IN_ZERO")
    w("static const float kModelNormMean[MODEL_FEATS] = {")
    w("    " + ", ".join(f"{v:.9g}f" for v in mean))
    w("};")
    w("static const float kModelQuantMul[MODEL_FEATS] = {")
    w("    " + ", ".join(f"{1.0 / (s * in_scale):.9g}f" for s in scale))
    w("};")
    w("")
    Path(out_path).write_text("\n".join(L) + "\n")
    print(f"wrote {out_path}: outputs beat={by_name['beat']} "
          f"beat_offset={by_name['beat_offset']} hit={by_name['hit']}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3], int(sys.argv[4]))
